---
title: "Day Care Fines"
output: 
  html_document:
    theme: cerulean
    code_folding: hide
---


```{r, warning=FALSE, message=FALSE}
library(mosaic)
library(DT)
library(pander)
library(car)
library(tidyverse)

# To get the "late" dataset into your R Console, 
# you need to go to your file menu of R-Studio and select
# "Session, Set working directory, To source file location"
# Then click the green "play" arrow in 
# the top right corner of this gray R-Chunk. 

## Wide data from original article:
late <- read.csv("../../../Data/late.csv", header=TRUE) 

## Change to "long" data for use in R:
Late <- pivot_longer(late, #Start with wide data set late
               cols = starts_with("Week"), #Find columns to gather from long data
               names_to = "Week", #New column name of Weeks in long data
               names_prefix = "Week", #Remove prefix of Week from Week1, Week2, ...
               names_transform = list(Week= ~as.numeric(.x)), #Make Week a numeric column of data
               values_to = "NumberofLateChildren") #Name of data column in long data

```



<!--If you want to give your critiquers some ideas about what you have questions on and would like help with, place those details here.-->



<!--End your comments to your critiquers before this line.-->

----


## Background {.tabset .tabset-fade}


### Study Details

<div style="color:#a8a8a8;">
This background is quoted directly from the article ["A Fine is a Price"](http://rady.ucsd.edu/faculty/directory/gneezy/pub/docs/fine.pdf). 
</div>

<div style="padding-left:30px; padding-right:30px;">

There are two types of day-care centers in Israel: private and public. A study was conducted in 10 private day-care centers in the city of Haifa from January to June 1998. All of these centers are located in the same part of town, and there is no important difference among them. During the day children are organized into groups according to age, from 1 to 4 years old. Each day-care center is allowed to hold a maximum of 35 children. In some exceptional cases a few additional children are allowed. The fee for each child is NIS 1,400 per month. (The NIS is the New Israeli Shekel.) At the time of the study, a U.S. dollar was worth approximately NIS 3.68, so the fee was about $380 at that time. 

The contract signed at the beginning of the year states that the day-care
center operates between 0730 and 1600. There is no mention of what happens if parents come late to pick up their children. In particular, before the beginning of the study, there was no fine for coming late. When parents did not come on time, one of the teachers had to wait with the children concerned. Teachers would rotate in this task, which is considered part of the job of a teacher, a fact that is clearly explained when a teacher is hired. Parents rarely came after 1630. 

A natural option [to fix the problem of parents showing up late] is to introduce a fine: every time a parent comes late, [they] will have to pay a fine. Will that reduce the number of parents who come late? If the fine is removed, will things revert back to the way they were originally?

The overall period of the study was 20 weeks. In the first 4 weeks we
simply recorded the number of parents who arrived late each week. At the
beginning of the fifth week, we introduced a fine in six of the 10 day-care centers, which had been selected randomly. The announcement of the fine was made with a note posted on the bulletin board of the day-care center. Parents tend to look at this board every day, since important announcements are posted there. The announcement specified that the fine would be NIS 10 for a delay of 10 minutes or more. The fine was per child; thus, if parents had two children in the center and they came late, they had to pay NIS 20. Payment was made to the principal of the day-care center at the end of the month. Since monthly payments are made to the owner during the year, the fines were added to those amounts. The money was paid to the owner, rather then to the teacher who was staying late (and did not get any additional money). The teachers were informed of the fine but not of the study. Registering the names of parents who came late was a common practice in any case.

At the beginning of the seventeenth (17th) week, the fine was removed with no explanation. Notice of the cancellation was posted on the board. If parents asked why the fines were removed, the principals were instructed to reply that the fine had been a trial for a limited time and that the results of this trial were now being evaluated.

A comparison with other fines in Israel may give an idea of the size of
the penalty that was introduced. A fine of NIS 10 is relatively small but not insignificant. In comparison, the fine for illegal parking is NIS 75; the fine for driving through a red light is NIS 1,000 plus penalties; the fine for not collecting the droppings of a dog is NIS 360. For many of these violations, however, detection and enforcement are low or, as in the case of dog dirt, nonexistent in practice. A baby-sitter earns between NIS 15 and NIS 20 per hour. The average gross salary per month in Israel at the time of the study was NIS 5,595.

</div>


### The Data (Wide)


The `late` Day Care Center data is shown here in the "wide data format" that was provided by the authors of the original research article. But this format is not terribly useful for an ANOVA analysis.

```{r, out.width=300}
#Show the full width of the "Wide" version of the late data:
pander(late, split.tables = Inf)
```


### The Data (Long)

The `Late` Day Care Center data is shown here in the "long data format", a more useable format for analysis.

```{r}
pander(Late)
```


 
##  


----



## Analysis {.tabset .tabset-fade}

### Hypotheses

<!-- State the hypotheses for this analysis in this section. -->



### Two-way ANOVA 

<!-- Show the two-way ANOVA summary output in this section. -->




### Graphics & Numerical Summaries

<!-- Show the three graphics of the two-way ANOVA in this section and provide a supporting table of numerical summaries for each graphic. -->





### Conclusions

<!-- Interpret the results of the study. Use specific details in your writing like mentioning the actual amount of the fine and the relative cost to babysitting. Mention the average number of late children before the fine, during the fine, and after the fine was removed. -->



### Diagnostic Plots

<!-- Provide some discussion about how appropriate the ANOVA analysis was for this data. Include the residuals vs. fitted values plot and the Q-Q Plot of residuals. -->



