---
title: "R Cheat Sheets & Notes"
---

## Cheat Sheets

* [R Colors](http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf)

* [R Base Graphics Cheat Sheet](http://www.joyce-robbins.com/wp-content/uploads/2016/04/BaseGraphicsCheatsheet.pdf)

* [R Base Commands Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2016/10/r-cheat-sheet-3.pdf)

* [R Markdown Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)

* [Keyboard Shortcuts](https://support.rstudio.com/hc/en-us/articles/200711853-Keyboard-Shortcuts)

## Notes

Add your own notes here...

```{r}
# Add R commands you want to remember here...

```

```{r}
# Or create other R chunks to put them in like this...

```

```{r, eval=FALSE}
# Using ```{r, eval=FALSE} turns off the chunk, but still shows it.
# Useful when you want to remember code, but not run it in this file.
```




```{r, eval=FALSE}
set.seed(15)

#Step 1
myTest <- t.test(length ~ sex, data=KidsFeet)
observedTestStat <- myTest$statistic
observedTestStat

#Step 2
N <- 2000
permutedTestStats <- rep(NA, 2000)
for (i in 1:N){
  permutedData <- sample(KidsFeet$length)
  permutedTest <- t.test(permutedData ~ sex, data=KidsFeet)
  permutedTestStats[i] <- permutedTest$statistic
}
hist(permutedTestStats)
abline(v=observedTestStat, col="red")

#Step 3
2*sum(permutedTestStats >= observedTestStat)/N
```




