---
title: "Chocolate"
output: 
  html_document:
    theme: cerulean
    code_folding: hide
---

```{r, include=FALSE}
# Be sure to use your file menus at the top of R-Studio to:
# "Session -> Set working directory -> To source file location"
# Then play this chunk and the next one to get the data into R.
library(mosaic)
library(car)
library(DT)
library(pander)
library(readr)
choc <- read_csv("../Data/Chocolate.csv")
```

```{r, eval=FALSE}
View(choc)
```

----

<!-- Instructions:

 Use the Chocolate dataset and a Kruskal-Wallis Test(s) to answer an interesting question(s) that you come up with.
 
 About the dataset:
 
  * Company: Name of the company manufacturing the bar.

  * Orig: The specific geo-region of origin for the bar.

  * Review: Date of publication of the review.

  * Cocoa: Cocoa percentage (darkness) of the chocolate bar being reviewed.

  * Location: Manufacturer base country.

  * Rating: Expert rating for the bar.
      5= Elite (Transcending beyond the ordinary limits)
      4= Premium (Superior flavor development, character and style)
      3= Satisfactory(3.0) to praiseworthy(3.75) (well made with special qualities)
      2= Disappointing (Passable but contains at least one significant flaw)
      1= Unpleasant (mostly unpalatable)

   * Type: The variety (breed) of cocoa bean used, if provided.
   
   * BroadOrig: The broad geo-region of origin for the bean.

Note this dataset and description come from: © 2018 Kaggle Inc for further details visit:

[Kaggle.com](https://www.kaggle.com/rtatman/chocolate-bar-ratings/data)


If you want to give your critiquers some ideas about what you have questions on and would like help with, place those details here.-->
**Comments to Critiquers:** 



<!--End your comments to your critiquers before this line.-->

----

<!--Begin writing your Analysis after this point.-->

## Background






